In [6]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
from scipy import stats
import json

In [7]:
with open('/Users/patrickburke/OneDrive_EmoryUniversity/Econ372/FinalProject/Bronx/Montefiore Medical Center/131740114_MMC_Standard_Charges.json') as mont:
    mont_data = json.load(mont)

In [8]:
df = pd.DataFrame.from_dict(mont_data, orient='index')

In [10]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,108531,108532,108533,108534,108535,108536,108537,108538,108539,108540
columns,Hospital,CODETYPE,PROCEDURE,CPT,REV_CODE,PROCEDURE_DESCRIPTION,PATIENT_TYPE,Gross Charges,Cash Price,1199 COMMERICAL,...,None,None,None,None,None,None,None,None,None,None
index,0,1,2,3,4,5,6,7,8,9,...,108531,108532,108533,108534,108535,108536,108537,108538,108539,108540
data,"[MMC, DRG, APR001, None, None, Liver Transplan...","[MMC, DRG, APR002, None, None, Heart &/Or Lung...","[MMC, DRG, APR003, None, None, Bone Marrow Tra...","[MMC, DRG, APR004, None, None, Tracheostomy W ...","[MMC, DRG, APR005, None, None, Tracheostomy W ...","[MMC, DRG, APR006, None, None, Pancreas Transp...","[MMC, DRG, APR020, None, None, Craniotomy For ...","[MMC, DRG, APR021, None, None, Craniotomy Exce...","[MMC, DRG, APR022, None, None, Ventricular Shu...","[MMC, DRG, APR023, None, None, Spinal Procedur...",...,"[MMC, SUP, Z285925, None, 0278 - MEDICAL/SURGI...","[MMC, SUP, Z285970, None, 0278 - MEDICAL/SURGI...","[MMC, SUP, M50006, None, 0278 - MEDICAL/SURGIC...","[MMC, SUP, TCDS0203-NT, None, 0624 - MEDICAL S...","[MMC, SUP, 107754, None, 0624 - MEDICAL SURGIC...","[MMC, SUP, 95858, J7297, 0636 - PHARMACY - EXT...","[MMC, None, None, None, None, None, OP, 992 , ...","[MMC, None, None, None, None, None, OP, 1,596 ...","[MMC, SUP, 141125, Q9966, 0636 - PHARMACY - EX...","[MMC, SUP, 131705, Q9966, 0636 - PHARMACY - EX..."

In [11]:
df = df.transpose()

In [12]:
df.head()

     columns index                                               data
0   Hospital     0  [MMC, DRG, APR001, None, None, Liver Transplan...
1   CODETYPE     1  [MMC, DRG, APR002, None, None, Heart &/Or Lung...
2  PROCEDURE     2  [MMC, DRG, APR003, None, None, Bone Marrow Tra...
3        CPT     3  [MMC, DRG, APR004, None, None, Tracheostomy W ...
4   REV_CODE     4  [MMC, DRG, APR005, None, None, Tracheostomy W ...

In [13]:
column_list = mont_data['columns']

In [12]:
column_list

['Hospital',
 'CODETYPE',
 'PROCEDURE',
 'CPT',
 'REV_CODE',
 'PROCEDURE_DESCRIPTION',
 'PATIENT_TYPE',
 'Gross Charges',
 'Cash Price',
 '1199 COMMERICAL',
 'AETNA ASA',
 'AETNA COMMERCIAL',
 'AFFINITY CHILD HEALTH PLUS',
 'AFFINITY MEDICAID',
 'AGEWELL NY',
 'CARE CONNECT',
 'CENTERS PLAN',
 'CIGNA HMO',
 'CIGNA PPO',
 'CIGNA SA',
 'EMBLEM HEALTH SELECT CARE',
 'EMPIRE BCBS HEALTHPLUS EP 1 & 2',
 'EMPIRE EXCHANGE',
 'EMPIRE HMO',
 'EMPIRE INDEMNITY',
 'EMPIRE MEDICARE MANAGED CARE',
 'EMPIRE PPO',
 'EMPIREBCBS HP CHP B',
 'ESSENTIAL PLANS 1-2',
 'ESSENTIAL PLANS EMBLEM',
 'ESSENTIALS PLAN 3-4',
 'FIDELIS CHP',
 'FIDELIS EXCHANGE',
 'FIDELIS MEDICAID',
 'FIDELIS MEDICARE',
 'GHI COMMERCIAL',
 'HB CENTERLIGHT MEDICARE MANAGED CARE',
 'HB FIDELIS ESSENTIAL 3-4',
 'HB FIDELIS ESSENTIAL PLAN 1-2',
 'HB MCR Affinity Essentials 1&2',
 'HB OSCAR',
 'HB WELLCARE CHP',
 'HB WELLCARE MEDICAID',
 'HB Wellcare Medicare',
 'HEALTHFIRST EP 1&2',
 'HEALTHFIRST HFIC',
 'HEALTHFIRST MEDICAID CHP',
 'HEALTHFIRST MEDICAID',
 'HEALTHFIRST MEDICARE IN NETWORK',
 'HEALTHFIRST MEDICARE OUT OF NETWORK',
 'HEALTHFIRST QHP/LEAF',
 'HEALTHPLUS AMERIGROUP MEDICAID',
 'HIP COMM EPO/PPO',
 'HIP HMO',
 'MEDICAID FFS',
 'MEDICARE FFS',
 'MEDICARE MANAGED CARE',
 'METROPLUS EP 1&2',
 'METROPLUS EXCHANGE',
 'METROPLUS MEDICAID',
 'NO FAULT & W/C',
 'OXFORD ASO',
 'OXFORD FREEDOM LIBERTY',
 'SOMOS CHP',
 'SOMOS EP 1&2',
 'SOMOS MEDICAID, HARP, EP 3&4',
 'UHC DSNP',
 'UNITED COMMUNITY PLAN MEDICAID',
 'UNITED',
 'MIN',
 'MAX']

In [14]:
df.head()

     columns index                                               data
0   Hospital     0  [MMC, DRG, APR001, None, None, Liver Transplan...
1   CODETYPE     1  [MMC, DRG, APR002, None, None, Heart &/Or Lung...
2  PROCEDURE     2  [MMC, DRG, APR003, None, None, Bone Marrow Tra...
3        CPT     3  [MMC, DRG, APR004, None, None, Tracheostomy W ...
4   REV_CODE     4  [MMC, DRG, APR005, None, None, Tracheostomy W ...

In [15]:
data_list = []
for row in df.iterrows():
    data_list.append(row[1].data)
df2 = pd.DataFrame(data_list, columns=column_list)

In [16]:
df2.head()

,Hospital,CODETYPE,PROCEDURE,CPT,REV_CODE,PROCEDURE_DESCRIPTION,PATIENT_TYPE,Gross Charges,Cash Price,1199 COMMERICAL,...,OXFORD ASO,OXFORD FREEDOM LIBERTY,SOMOS CHP,SOMOS EP 1&2,"SOMOS MEDICAID, HARP, EP 3&4",UHC DSNP,UNITED COMMUNITY PLAN MEDICAID,UNITED,MIN,MAX
0,MMC,DRG,APR001,None,None,Liver Transplant &/Or Intestinal Transplant,IP,759194.83,493476.64,Not Applicable,...,Not Applicable,Not Applicable,133653.4,76058.66,133653.4,Not Applicable,133653.4,Not Applicable,64456.49,366599.25
1,MMC,DRG,APR002,None,None,Heart &/Or Lung Transplant,IP,935625.08,608156.3,Not Applicable,...,Not Applicable,Not Applicable,250079.92,964922.88,250079.92,Not Applicable,265577.72,Not Applicable,115210.81,964922.88
2,MMC,DRG,APR003,None,None,Bone Marrow Transplant,IP,469336.41,305068.67,Not Applicable,...,Not Applicable,Not Applicable,59762.84,148150.81,59762.84,Not Applicable,59762.84,Not Applicable,46134.33,599809.51
3,MMC,DRG,APR004,None,None,Tracheostomy W Mv 96+ Hours W Extensive Proced...,IP,1026707.93,667360.15,Not Applicable,...,Not Applicable,Not Applicable,137997.12,869611.38,137997.12,Not Applicable,137997.12,Not Applicable,74498.11,1074946.58
4,MMC,DRG,APR005,None,None,Tracheostomy W Mv 96+ Hours W/O Extensive Proc...,IP,624223.93,405745.55,Not Applicable,...,Not Applicable,Not Applicable,107941.02,699569,107941.02,Not Applicable,107941.02,Not Applicable,59880.82,699569.00

In [15]:
#df2.to_excel('/Users/patrickburke/OneDrive - Emory University/Econ372/Final Project/Bronx/Montefiore Medical Center/MontefioreRawFixed.xlsx')

In [17]:
#df2.to_csv('/Users/patrickburke/OneDrive - Emory University/Econ372/Final Project/Bronx/Montefiore Medical Center/MontefioreRawFixed.csv')